/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package page;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class AddPakan extends javax.swing.JDialog {

    /**
     * Creates new form AddPakan
     */
    private static boolean isAddNew = true;
    public AddPakan(java.awt.Frame parent, boolean modal, String idPakan) {
        super(parent, modal);
        initComponents();
        
       if(idPakan != null){
           isAddNew = false;
           tampilPakan(idPakan);
           
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtIdPakan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNamaPakan = new javax.swing.JTextField();
        cmbJenisPakan = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        simpanPakan = new javax.swing.JLabel();
        txtBeratKering = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtProteinKasar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEnergi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("X");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 40));
        jPanel1.add(txtIdPakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, 40));

        jLabel1.setText("ID Pakan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setText("Jenis Pakani");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        jLabel4.setText("Nama Pakan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        jPanel1.add(txtNamaPakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, 40));

        cmbJenisPakan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peranakan Ongole", "Simental", "Brangus", "PO Brahman", "Limousin" }));
        jPanel1.add(cmbJenisPakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 160, 40));

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        simpanPakan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        simpanPakan.setForeground(new java.awt.Color(255, 255, 255));
        simpanPakan.setText("SIMPAN");
        simpanPakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanPakanMouseClicked(evt);
            }
        });
        jPanel3.add(simpanPakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 160, 40));
        jPanel1.add(txtBeratKering, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 160, 40));

        jLabel7.setText("Berat Kering");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel1.add(txtProteinKasar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 160, 40));

        jLabel8.setText("Protein Kasar");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLabel9.setText("Energi");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));
        jPanel1.add(txtEnergi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanPakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanPakanMouseClicked
        // TODO add your handling code here:
        if(isAddNew == true){
            simpanPakan();
        }else{
            updatePakan();
        }
        
    }//GEN-LAST:event_simpanPakanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddPakan dialog = new AddPakan(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void tampilPakan(String idPakan){
         try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT * FROM pakan WHERE id_pakan = '"+idPakan+"'";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            
            if (hasil.next()) {
                txtIdPakan.setText(hasil.getString("id_pakan"));
                txtNamaPakan.setText(hasil.getString("nama_pakan"));
                cmbJenisPakan.setSelectedItem(hasil.getString("jenis_pakan"));
                txtBeratKering.setText(hasil.getString("berat_kering"));
                txtProteinKasar.setText(hasil.getString("protein_kasar"));
                txtEnergi.setText(hasil.getString("energi"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menampilkan Frame!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            this.setVisible(false);
        }
    }
    
    private void simpanPakan(){
        String idPakan, namaPakan, jenisPakan;
        double bk, pk, energi;
        
        idPakan = txtIdPakan.getText();
        namaPakan = txtNamaPakan.getText();
        bk = Double.parseDouble(txtBeratKering.getText()) ;
        pk = Double.parseDouble(txtProteinKasar.getText()) ;
        energi = Double.parseDouble(txtEnergi.getText()) ;
        jenisPakan = cmbJenisPakan.getSelectedItem().toString();
        
        if (empty(idPakan) || empty(namaPakan) || empty(jenisPakan) || bk==0 || pk==0 || energi==0 )  {
            JOptionPane.showMessageDialog(null, "Data yang Anda masukkan belum lengkap!", "Peringatan!", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Connection con = new database.connection().configDB();
                String get = "SELECT * FROM pakan WHERE id_pakan = '"+idPakan+"'";
                java.sql.Statement st = con.createStatement();
                java.sql.ResultSet hasil = st.executeQuery(get);
                
                if (hasil.next()) {
                    JOptionPane.showMessageDialog(null, "Id Pakan tidak boleh ada yang sama.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                } else {
                    try {
                        String sql = "INSERT INTO pakan VALUES (?, ?, ?, ?, ?, ?)";
                        java.sql.PreparedStatement stat = (PreparedStatement)con.prepareStatement(sql);
                        stat.setString(1, idPakan);
                        stat.setString(2, namaPakan);
                        stat.setString(3, jenisPakan);
                        stat.setDouble(4, bk);
                        stat.setDouble(5, pk);
                        stat.setDouble(6, energi);
                        stat.executeUpdate();
                        

                        this.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Data BERHASIL Ditambahkan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "GAGAL Menambahkan Data", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (Exception e) {}
        }
    }
    
    private void updatePakan(){
        String idPakan, namaPakan, jenisPakan;
        double bk, pk, energi;
        
        idPakan = txtIdPakan.getText();
        namaPakan = txtNamaPakan.getText();
        bk = Double.parseDouble(txtBeratKering.getText()) ;
        pk = Double.parseDouble(txtProteinKasar.getText()) ;
        energi = Double.parseDouble(txtEnergi.getText()) ;
        jenisPakan = cmbJenisPakan.getSelectedItem().toString();
        
        if (!empty(idPakan) || !empty(namaPakan) || !empty(jenisPakan)) {
            try {
                Connection con = new database.connection().configDB();
                String sql = "UPDATE pakan SET jenis_pakan = ?, berat_kering = ?, protein_kasar = ?, energi = ? WHERE id_pakan = '"+idPakan+"'";
                java.sql.PreparedStatement stat = con.prepareStatement(sql);
                stat.setString(1, jenisPakan);
                stat.setDouble(2, bk);
                stat.setDouble(3, pk);
                stat.setDouble(4, energi);
                stat.executeUpdate();
                
                this.setVisible(false);
                JOptionPane.showMessageDialog(null, "Data BERHASIL Diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
           
             } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "GAGAL Mengubah Data", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

     private static boolean empty(final String s) {
        return s == null || s.trim().isEmpty();
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbJenisPakan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel simpanPakan;
    private javax.swing.JTextField txtBeratKering;
    private javax.swing.JTextField txtEnergi;
    private javax.swing.JTextField txtIdPakan;
    private javax.swing.JTextField txtNamaPakan;
    private javax.swing.JTextField txtProteinKasar;
    // End of variables declaration//GEN-END:variables
}
