
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelPakan;
import model.Persentase;
import utils.KalkulasiUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class home1 extends javax.swing.JFrame {

    /**
     * Creates new form home1
     */
    public static final String HIJAUAN = "Hijauan";
    public static final String KONSENTRAT = "Konsentrat";
    private static DecimalFormat df2 = new DecimalFormat("#.###");
    
    DefaultTableModel tblSapi = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    DefaultTableModel tblKalkulasi = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    DefaultTableModel tblPakan = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    DefaultTableModel tblInputPakan = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    public home1() {
        initComponents();
        //tampilSapi();
        tampilPakan();
        
        Object []baris = {"Nama Pakan", "Persen"};
        tblInputPakan = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbInputPakan.setModel(tblInputPakan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        tambahK = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtNoReg = new javax.swing.JTextField();
        txtJenisSapi = new javax.swing.JTextField();
        txtBobotAwal = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtPbbh = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtBeratKering = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtProteinKasar = new javax.swing.JTextField();
        txtEnergi = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtJmlHari = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtBobotHarapan = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKalkulasi = new javax.swing.JTable();
        jLabel44 = new javax.swing.JLabel();
        txtTotalBk = new javax.swing.JTextField();
        txtTotalPk = new javax.swing.JTextField();
        txtTotalEnergi = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        btnKalkulasi = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnKalPak = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbInputPakan = new javax.swing.JTable();
        cmbPakan = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPersenPakan = new javax.swing.JTextField();
        btnInputPakan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        tambahSapi = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        ubahSapi = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        hapusSapi = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        perbaharuiSapi = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbSapi = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        tambahPakan = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        ubahPakan = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        hapusPakan = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        perbaharuiPakan = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPakan = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(148, 37, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("SISTEM MANAJEMEN PAKAN SAPI KURBAN");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 11, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("X");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("?");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 46));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jTabbedPane1AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jPanel10.setBackground(new java.awt.Color(153, 0, 0));
        jPanel10.setToolTipText("");
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });

        tambahK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tambahK.setForeground(new java.awt.Color(255, 255, 255));
        tambahK.setText("SIMPAN");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tambahK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(153, 0, 0));
        jPanel11.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("UBAH");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(153, 0, 0));
        jPanel12.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HAPUS");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(153, 0, 0));
        jPanel13.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PERBAHARUI");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 530));

        jLabel31.setText("No Reg Sapi");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 13, -1, -1));

        jLabel32.setText("Jenis Sapi");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel33.setText("Bobot Awal");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        txtNoReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoRegActionPerformed(evt);
            }
        });
        txtNoReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoRegKeyPressed(evt);
            }
        });
        jPanel4.add(txtNoReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 33, 80, -1));
        jPanel4.add(txtJenisSapi, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 80, -1));

        txtBobotAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBobotAwalActionPerformed(evt);
            }
        });
        jPanel4.add(txtBobotAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 80, -1));

        jLabel34.setText("PBBH");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        txtPbbh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPbbhActionPerformed(evt);
            }
        });
        jPanel4.add(txtPbbh, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 80, -1));

        jLabel35.setText("Berat Kering");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 66, 99, -1));
        jPanel4.add(txtBeratKering, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 63, 90, -1));

        jLabel37.setText("Protein Kasar");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 97, -1, -1));
        jPanel4.add(txtProteinKasar, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 94, 90, -1));
        jPanel4.add(txtEnergi, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 125, 90, -1));

        jLabel38.setText("Energi");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 128, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Kebutuhan Pakan Ideal :");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 43, -1, -1));

        txtJmlHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmlHariActionPerformed(evt);
            }
        });
        jPanel4.add(txtJmlHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 80, -1));

        jLabel39.setText("Jml Hari Perawatan");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 100, -1, -1));

        txtBobotHarapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBobotHarapanActionPerformed(evt);
            }
        });
        jPanel4.add(txtBobotHarapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 17, 90, -1));

        jLabel40.setText("Bobot Harapan");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 20, -1, -1));

        tbKalkulasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID Pakan", "Nama Pakan", "Jenis Pakan", "Berat Kering", "Protein Kasar", "Energi"
            }
        ));
        jScrollPane1.setViewportView(tbKalkulasi);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 573, 122));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel44.setText("Tabel Kandungan Nutrisi Pakan");
        jPanel4.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));
        jPanel4.add(txtTotalBk, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 68, -1));
        jPanel4.add(txtTotalPk, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, 68, -1));
        jPanel4.add(txtTotalEnergi, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, 68, -1));

        jLabel45.setText("TOTAL");
        jPanel4.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, -1, 20));

        btnKalkulasi.setBackground(new java.awt.Color(153, 0, 0));
        btnKalkulasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKalkulasiMouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kalkulasi");
        btnKalkulasi.add(jLabel2);

        jPanel4.add(btnKalkulasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 91, -1));

        btnKalPak.setBackground(new java.awt.Color(153, 0, 0));
        btnKalPak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKalPakMouseClicked(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("kalkulasi Pakan");
        btnKalPak.add(jLabel11);

        jPanel4.add(btnKalPak, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 91, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Pakan"));

        tbInputPakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane5.setViewportView(tbInputPakan);

        jLabel43.setText("Input Pakan");

        jLabel7.setText("Persen");

        btnInputPakan.setBackground(new java.awt.Color(153, 0, 0));
        btnInputPakan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInputPakan.setForeground(new java.awt.Color(255, 255, 255));
        btnInputPakan.setText("Simpan");
        btnInputPakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInputPakanMouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Hapus");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cmbPakan, 0, 122, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtPersenPakan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(btnInputPakan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(5, 5, 5)
                        .addComponent(cmbPakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPersenPakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInputPakan)
                            .addComponent(jButton2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, 180));

        jTabbedPane1.addTab("HOME", jPanel4);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel20.setPreferredSize(new java.awt.Dimension(161, 425));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBackground(new java.awt.Color(153, 0, 0));
        jPanel21.setToolTipText("");
        jPanel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel21MouseClicked(evt);
            }
        });

        tambahSapi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tambahSapi.setForeground(new java.awt.Color(255, 255, 255));
        tambahSapi.setText("TAMBAH");
        tambahSapi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahSapiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tambahSapi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tambahSapi)
                .addContainerGap())
        );

        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 198, 123, -1));

        jPanel22.setBackground(new java.awt.Color(153, 0, 0));
        jPanel22.setToolTipText("");

        ubahSapi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ubahSapi.setForeground(new java.awt.Color(255, 255, 255));
        ubahSapi.setText("UBAH");
        ubahSapi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ubahSapiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(ubahSapi)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ubahSapi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel20.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 255, -1, -1));

        jPanel23.setBackground(new java.awt.Color(153, 0, 0));
        jPanel23.setToolTipText("");

        hapusSapi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hapusSapi.setForeground(new java.awt.Color(255, 255, 255));
        hapusSapi.setText("HAPUS");
        hapusSapi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusSapiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(hapusSapi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hapusSapi)
                .addContainerGap())
        );

        jPanel20.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 317, 123, -1));

        jPanel24.setBackground(new java.awt.Color(153, 0, 0));
        jPanel24.setToolTipText("");

        perbaharuiSapi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        perbaharuiSapi.setForeground(new java.awt.Color(255, 255, 255));
        perbaharuiSapi.setText("PERBAHARUI");
        perbaharuiSapi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perbaharuiSapiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(perbaharuiSapi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(perbaharuiSapi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel20.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 374, 123, -1));

        jLabel15.setToolTipText("");
        jPanel20.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 21, -1, 46));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 530));

        tbSapi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "No Reg Sapi", "Jenis", "Bobot Awal"
            }
        ));
        jScrollPane3.setViewportView(tbSapi);

        jPanel19.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 570, 530));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("MASTER SAPI", jPanel5);

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel27.setBackground(new java.awt.Color(153, 0, 0));
        jPanel27.setToolTipText("");

        tambahPakan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tambahPakan.setForeground(new java.awt.Color(255, 255, 255));
        tambahPakan.setText("TAMBAH");
        tambahPakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahPakanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tambahPakan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tambahPakan)
                .addContainerGap())
        );

        jPanel26.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 198, 123, -1));

        jPanel28.setBackground(new java.awt.Color(153, 0, 0));
        jPanel28.setToolTipText("");

        ubahPakan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ubahPakan.setForeground(new java.awt.Color(255, 255, 255));
        ubahPakan.setText("UBAH");
        ubahPakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ubahPakanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(ubahPakan)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ubahPakan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel26.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 255, -1, -1));

        jPanel29.setBackground(new java.awt.Color(153, 0, 0));
        jPanel29.setToolTipText("");

        hapusPakan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hapusPakan.setForeground(new java.awt.Color(255, 255, 255));
        hapusPakan.setText("HAPUS");
        hapusPakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusPakanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(hapusPakan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel29Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hapusPakan)
                .addContainerGap())
        );

        jPanel26.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 317, 123, -1));

        jPanel30.setBackground(new java.awt.Color(153, 0, 0));
        jPanel30.setToolTipText("");

        perbaharuiPakan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        perbaharuiPakan.setForeground(new java.awt.Color(255, 255, 255));
        perbaharuiPakan.setText("PERBAHARUI");
        perbaharuiPakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perbaharuiPakanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(perbaharuiPakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(perbaharuiPakan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel26.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 374, 123, -1));

        jLabel20.setToolTipText("");
        jPanel26.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 21, -1, 46));

        jPanel25.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 530));

        tbPakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID Pakan", "Nama Pakan", "Jenis Pakan", "Berat Kering", "Protein Kasar", "Energi"
            }
        ));
        jScrollPane2.setViewportView(tbPakan);

        jPanel25.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 570, 530));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("MASTER PAKAN", jPanel6);

        jPanel37.setBackground(new java.awt.Color(255, 255, 255));
        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel39.setBackground(new java.awt.Color(153, 0, 0));
        jPanel39.setToolTipText("");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("TAMBAH");

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel39Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addContainerGap())
        );

        jPanel38.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 198, 123, -1));

        jPanel40.setBackground(new java.awt.Color(153, 0, 0));
        jPanel40.setToolTipText("");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("UBAH");

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel27)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel38.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 255, -1, -1));

        jPanel41.setBackground(new java.awt.Color(153, 0, 0));
        jPanel41.setToolTipText("");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("HAPUS");

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel41Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addContainerGap())
        );

        jPanel38.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 317, 123, -1));

        jPanel42.setBackground(new java.awt.Color(153, 0, 0));
        jPanel42.setToolTipText("");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("PERBAHARUI");

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel38.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 374, 123, -1));

        jLabel30.setToolTipText("");
        jPanel38.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 21, -1, 46));

        jPanel37.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 530));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "No Reg Sapi", "", "Jenis Sapi", "Bobot Awal", "PBBH", "Jml Hari Perawatan", "Pakan", "Bobot Aktual", "Real PBBH"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel37.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 570, 530));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel37, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel37, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("LAPORAN", jPanel8);

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("@Copyright - Faisal fahmi Al Hasani - 2020");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Home");

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 52, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabbedPane1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1AncestorMoved

    private void tambahSapiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahSapiMouseClicked
        new page.AddSapi(this, rootPaneCheckingEnabled, null).setVisible(true);
    }//GEN-LAST:event_tambahSapiMouseClicked

    private void jPanel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel21MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel21MouseClicked

    private void ubahSapiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahSapiMouseClicked
        // TODO add your handling code here:
        int baris = tbSapi.getSelectedRow();
        if (baris >= 0) {
            String noReg = tbSapi.getValueAt(baris, 1).toString();
            try {
                Connection con = new database.connection().configDB();
                String sql = "SELECT * FROM sapi WHERE no_reg = '"+noReg+"'";
                java.sql.Statement st = con.createStatement();
                java.sql.ResultSet rs = st.executeQuery(sql);
                
                if (rs.next()) {
                    String id = rs.getString("no_reg");
                    new page.AddSapi(this, rootPaneCheckingEnabled, id).setVisible(true);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal menyeleksi data!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Anda belum memilih data yang akan diubah!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ubahSapiMouseClicked

    private void perbaharuiSapiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perbaharuiSapiMouseClicked
        // TODO add your handling code here:
        tampilSapi();
    }//GEN-LAST:event_perbaharuiSapiMouseClicked

    private void hapusSapiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusSapiMouseClicked
       int baris = tbSapi.getSelectedRow();
        if (baris >= 0) {
            String noReg = tbSapi.getValueAt(baris, 1).toString();
            String jenis = tbSapi.getValueAt(baris, 2).toString();

            int x = JOptionPane.showConfirmDialog(null, "Data Sapi dengan\n\nNoReg: "+noReg+"\njenis: "+jenis+"\n\nakan Anda hapus, yakin?\n", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (x == JOptionPane.YES_OPTION) {
                try {
                    Connection con = new database.connection().configDB();
                    String sql = "DELETE FROM sapi WHERE no_reg = '"+noReg+"'";
                    java.sql.Statement st = con.createStatement();
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    tampilSapi();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Gagal menghapus data!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Anda belum memilih data yang akan dihapus!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_hapusSapiMouseClicked

    private void tambahPakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahPakanMouseClicked
        new page.AddPakan(this, rootPaneCheckingEnabled, null).setVisible(true);
    }//GEN-LAST:event_tambahPakanMouseClicked

    private void perbaharuiPakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perbaharuiPakanMouseClicked
        tampilPakan();
    }//GEN-LAST:event_perbaharuiPakanMouseClicked

    private void ubahPakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahPakanMouseClicked
         int baris = tbPakan.getSelectedRow();
        if (baris >= 0) {
            String id_pakan = tbPakan.getValueAt(baris, 1).toString();
            try {
                Connection con = new database.connection().configDB();
                String sql = "SELECT * FROM pakan WHERE id_pakan = '"+id_pakan+"'";
                java.sql.Statement st = con.createStatement();
                java.sql.ResultSet rs = st.executeQuery(sql);
                
                if (rs.next()) {
                    String id = rs.getString("id_pakan");
                    new page.AddPakan(this, rootPaneCheckingEnabled, id).setVisible(true);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal menyeleksi data!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Anda belum memilih data yang akan diubah!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ubahPakanMouseClicked

    private void hapusPakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusPakanMouseClicked
        int baris = tbPakan.getSelectedRow();
        if (baris >= 0) {
            String idPakan = tbPakan.getValueAt(baris, 1).toString();
            String namaPakan = tbPakan.getValueAt(baris, 2).toString();

            int x = JOptionPane.showConfirmDialog(null, "Data Pakan dengan\n\nId Pakan: "+idPakan+"\nNama Pakan: "+namaPakan+"\n\nakan Anda hapus, yakin?\n", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (x == JOptionPane.YES_OPTION) {
                try {
                    Connection con = new database.connection().configDB();
                    String sql = "DELETE FROM pakan WHERE id_pakan = '"+idPakan+"'";
                    java.sql.Statement st = con.createStatement();
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    tampilSapi();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Gagal menghapus data!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Anda belum memilih data yang akan dihapus!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_hapusPakanMouseClicked

    private void btnKalPakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKalPakMouseClicked
        double ransum = Double.parseDouble(txtBeratKering.getText());
        double proteinKasar = Double.parseDouble(txtProteinKasar.getText());
        double energi = Double.parseDouble(txtEnergi.getText());

        double rasioKonsentrat = KalkulasiUtils.beratPakanByRasio(40, ransum);
        double rasioHijauan = KalkulasiUtils.beratPakanByRasio(60, ransum);

    

        
        Map<String,Double> persenDouble = new HashMap();
        List<String> listInputPakan = new ArrayList();
       
        for (int i=0; i < tbInputPakan.getRowCount(); i++){    
            String pakan = tbInputPakan.getValueAt(i, 0).toString();
            double persen = (Double) tbInputPakan.getValueAt(i, 1);
            persenDouble.put(pakan,persen);
            listInputPakan.add(pakan);
        }

        List<ModelPakan> listPakan = findPakanByList(listInputPakan);

        List<ModelPakan> pakanCalculatedList = new ArrayList<>();

        for (ModelPakan pakan : listPakan) {
            ModelPakan calculated = new ModelPakan();
            calculated.setIdPakan(pakan.getIdPakan());
            calculated.setNamaPakan(pakan.getNamaPakan());

            if(pakan.getJenisPakan().equalsIgnoreCase(HIJAUAN)){
                setNutrisiByPersentase(calculated, pakan, persenDouble, rasioHijauan);  
            }else if (pakan.getJenisPakan().equals(KONSENTRAT)){
                setNutrisiByPersentase(calculated, pakan, persenDouble, rasioKonsentrat);
            }
            pakanCalculatedList.add(calculated);
        }

        Object []baris = {"No", "Id Pakan", "Nama Pakan", "Jenis Pakan", "Berat Segar", "Berat Kering", "Protein Kasar", "Energi"};
        tblKalkulasi = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbKalkulasi.setModel(tblKalkulasi);
        int i = 1;
        for (ModelPakan modelPakan : pakanCalculatedList) {
            Object[] data = {i++, modelPakan.getIdPakan(), modelPakan.getNamaPakan(), modelPakan.getJenisPakan(),
                df2.format(modelPakan.getBeratSegar()), df2.format(modelPakan.getBeratKering()),
                df2.format(modelPakan.getProteinKasar()), df2.format(modelPakan.getEnergi())};
            tblKalkulasi.addRow(data);
        }
        double proteinTotal = 0, energiTotal = 0, beratKeringTotal = 0;
        for (ModelPakan pakan : pakanCalculatedList) {
            proteinTotal = proteinTotal + pakan.getProteinKasar();
            energiTotal = energiTotal + pakan.getEnergi();
            beratKeringTotal = beratKeringTotal + pakan.getBeratKering();
        }
        txtTotalBk.setText(df2.format(beratKeringTotal));
        txtTotalEnergi.setText(df2.format(energiTotal));
        txtTotalPk.setText(df2.format(proteinTotal));
    }//GEN-LAST:event_btnKalPakMouseClicked

    private void btnKalkulasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKalkulasiMouseClicked
        int bobotAwal = Integer.parseInt(txtBobotAwal.getText());
        double pbbh = Double.parseDouble(txtPbbh.getText());
        int jmlHari = Integer.parseInt(txtJmlHari.getText());

        //hitung Bobot Ideal
        txtBobotHarapan.setText(df2.format(KalkulasiUtils.bobotHarapan(jmlHari, pbbh, bobotAwal)));

        //hitung bahanKering
        double ransum = KalkulasiUtils.ransum(bobotAwal);
        txtBeratKering.setText(df2.format(ransum));

        //hitung total PK
        double kebProteinMin = KalkulasiUtils.kebProteinMin(ransum);
        txtProteinKasar.setText(df2.format(kebProteinMin));

        //hitung total Energi
        double kebEnergiMin = KalkulasiUtils.kebEnergiMin(ransum);
        txtEnergi.setText(df2.format(kebEnergiMin));
    }//GEN-LAST:event_btnKalkulasiMouseClicked

    private void txtBobotHarapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBobotHarapanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBobotHarapanActionPerformed

    private void txtJmlHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmlHariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJmlHariActionPerformed

    private void txtPbbhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPbbhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPbbhActionPerformed

    private void txtBobotAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBobotAwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBobotAwalActionPerformed

    private void txtNoRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoRegKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            searchSapi();
            
        }
    }//GEN-LAST:event_txtNoRegKeyPressed

    private void txtNoRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoRegActionPerformed

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10MouseClicked

    private void btnInputPakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputPakanMouseClicked
        // TODO add your handling code here:
        String pakan = cmbPakan.getSelectedItem().toString();
        double persen = Double.parseDouble(txtPersenPakan.getText());
       
        Object[] data = {pakan, persen};
        tblInputPakan.addRow(data);
        
    }//GEN-LAST:event_btnInputPakanMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        int baris = tbInputPakan.getSelectedRow();
        tblInputPakan.removeRow(baris);
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home1().setVisible(true);
            }
        });
    }
    
    private void setNutrisiByPersentase(ModelPakan calculated, ModelPakan pakan, Map<String,Double> persentase, double rasio){
        calculated.setJenisPakan(pakan.getJenisPakan());
        double pers = persentase.get(pakan.getNamaPakan());
        double aktualBeratPakan = pers/100 * rasio;

        calculated.setBeratKering(aktualBeratPakan);
        calculated.setEnergi(KalkulasiUtils.nilaiNutrisi(pakan.getEnergi(), aktualBeratPakan));
        calculated.setProteinKasar(KalkulasiUtils.nilaiNutrisi(pakan.getProteinKasar(), aktualBeratPakan));
        calculated.setBeratSegar(KalkulasiUtils.bahanSegarPakan(aktualBeratPakan, pakan.getBeratKering()));
    }
    
    private void searchSapi() {
        String reg = txtNoReg.getText();
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT * FROM sapi WHERE "
                    + "no_reg = '"+reg+"' ";
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet hasil = stmt.executeQuery(sql);
            
            while (hasil.next()) {
                String jenis = hasil.getString("jenis");
                String bobot = hasil.getString("bobot_awal");
                
                txtJenisSapi.setText(jenis);
                txtBobotAwal.setText(bobot);
                
                
            }
        } catch (Exception e) {
        
        }
    }
    
    private List<ModelPakan> findPakanByList(List<String> listPakanInput){
        List<ModelPakan> listPakan = new ArrayList<>();
        String queryName = listPakanInput.stream()
               .map(s -> "'"+s+"'")
               .collect(Collectors.joining(",", "(", ")"));
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT * FROM pakan WHERE nama_pakan IN "+queryName+" "
                    + " ORDER BY id_pakan ASC";
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet hasil = stmt.executeQuery(sql);
            
            while (hasil.next()) {
                ModelPakan pakan = new ModelPakan();
                pakan.setIdPakan(hasil.getString("id_pakan"));
                pakan.setNamaPakan(hasil.getString("nama_pakan"));
                pakan.setJenisPakan(hasil.getString("jenis_pakan"));
                pakan.setBeratKering(hasil.getDouble("berat_kering"));
                pakan.setProteinKasar(hasil.getDouble("protein_kasar"));
                pakan.setEnergi(hasil.getDouble("energi"));
                
                listPakan.add(pakan);
             }
        } catch (Exception e) {
            System.out.print("GAGAL AMBIL LIST PAKAN " + e);
        }
        
        return listPakan;
    }

    
    public void tampilSapi() {
        Object []baris = {"no", "No Reg", "Jenis", "Bobot Cuy"};
        tblSapi = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbSapi.setModel(tblSapi);
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT * FROM sapi ORDER BY no_reg ASC";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            int i = 1;
            while (hasil.next()) {
                int no = i++;
                String noReg = hasil.getString("no_reg");
                String jenis = hasil.getString("jenis");
                int bobot = hasil.getInt("bobot_awal");
                
                Object[] data = {no, noReg, jenis, bobot};
                tblSapi.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan DATA!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
            dispose();
        }
    }
    
    public void tampilPakan() {
        Object []baris = {"No", "Id Pakan", "Nama Pakan", "Jenis Pakan", "Berat Kering", "Protein Kasar", "Energi"};
        tblPakan = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbPakan.setModel(tblPakan);
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT * FROM pakan ORDER BY id_pakan ASC";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            int i = 1;
            while (hasil.next()) {
                int no = i++;
                String idPakan = hasil.getString("id_pakan");
                String namaPakan = hasil.getString("nama_pakan");
                String jenisPakan = hasil.getString("jenis_pakan");
                double beratKering = hasil.getDouble("berat_kering");
                double proteinKasar = hasil.getDouble("protein_kasar");
                double energi = hasil.getDouble("energi");
                
                Object[] data = {no, idPakan, namaPakan, jenisPakan, beratKering, proteinKasar, energi};
                tblPakan.addRow(data);
                cmbPakan.addItem(namaPakan);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan DATA!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
            dispose();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInputPakan;
    private javax.swing.JPanel btnKalPak;
    private javax.swing.JPanel btnKalkulasi;
    private javax.swing.JComboBox<String> cmbPakan;
    private javax.swing.JLabel hapusPakan;
    private javax.swing.JLabel hapusSapi;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel perbaharuiPakan;
    private javax.swing.JLabel perbaharuiSapi;
    private javax.swing.JLabel tambahK;
    private javax.swing.JLabel tambahPakan;
    private javax.swing.JLabel tambahSapi;
    private javax.swing.JTable tbInputPakan;
    private javax.swing.JTable tbKalkulasi;
    private javax.swing.JTable tbPakan;
    private javax.swing.JTable tbSapi;
    private javax.swing.JTextField txtBeratKering;
    private javax.swing.JTextField txtBobotAwal;
    private javax.swing.JTextField txtBobotHarapan;
    private javax.swing.JTextField txtEnergi;
    private javax.swing.JTextField txtJenisSapi;
    private javax.swing.JTextField txtJmlHari;
    private javax.swing.JTextField txtNoReg;
    private javax.swing.JTextField txtPbbh;
    private javax.swing.JTextField txtPersenPakan;
    private javax.swing.JTextField txtProteinKasar;
    private javax.swing.JTextField txtTotalBk;
    private javax.swing.JTextField txtTotalEnergi;
    private javax.swing.JTextField txtTotalPk;
    private javax.swing.JLabel ubahPakan;
    private javax.swing.JLabel ubahSapi;
    // End of variables declaration//GEN-END:variables
}
